# Generated by Django 5.1.1 on 2024-10-03 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('impact_communautaire', models.TextField(help_text='En quoi ce projet va aider la communauté ?')),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='business_plans/')),
                ('autres_documents', models.FileField(blank=True, null=True, upload_to='autres_documents/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
