# Generated by Django 5.1.1 on 2024-10-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
