# Generated by Django 5.1.1 on 2024-10-06 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0004_alter_projet_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageadminpartner',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_admin_partner', to='projets.projet'),
        ),
        migrations.AlterField(
            model_name='messageadminpartner',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_partner', to='projets.customuser'),
        ),
        migrations.AlterField(
            model_name='messageadminpartner',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_partner', to='projets.customuser'),
        ),
        migrations.AlterField(
            model_name='messageuseradmin',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_user_admin', to='projets.projet'),
        ),
        migrations.AlterField(
            model_name='messageuseradmin',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_admin', to='projets.customuser'),
        ),
        migrations.AlterField(
            model_name='messageuseradmin',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_admin', to='projets.customuser'),
        ),
    ]
