# Generated by Django 5.1.1 on 2024-10-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_alter_messageadminpartner_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='icone',
            field=models.CharField(default='fas fa-project-diagram', max_length=50),
        ),
    ]
