# Generated by Django 5.1.1 on 2024-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_projet_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('under_validation', 'En cours de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
