# Generated by Django 5.1.1 on 2024-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0008_projet_financed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='has_team',
            field=models.BooleanField(default=False, verbose_name='Avez-vous une équipe ?'),
        ),
    ]
